services:

  cassandra:
    image: cassandra:3.11.2
    restart: unless-stopped
    container_name: cassandra
    ports:
      - "9042:9042"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: rmq
      RABBITMQ_DEFAULT_PASS: pass
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "./volumes/rabbitmq/:/etc/rabbitmq"

  postgres:
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser
      POSTGRES_DB: dbname
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/data/postgres
